SET IDENTITY_INSERT [dbo].[Country] ON
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (1, N'Norway', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (2, N'Switzerland', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (3, N'Ireland', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (4, N'Germany', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (5, N'Hong Kong, China (SAR)', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (6, N'Australia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (7, N'Iceland', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (8, N'Sweden', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (9, N'Singapore', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (10, N'Netherlands', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (11, N'Denmark', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (12, N'Finland', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (13, N'Canada', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (14, N'New Zealand', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (15, N'United Kingdom', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (16, N'United States', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (17, N'Belgium', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (18, N'Liechtenstein', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (19, N'Japan', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (20, N'Austria', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (21, N'Luxembourg', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (22, N'Israel', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (23, N'Korea (Republic of)', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (24, N'Slovenia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (25, N'Spain', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (26, N'Czechia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (27, N'France', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (28, N'Malta', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (29, N'Italy', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (30, N'Estonia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (31, N'Cyprus', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (32, N'Greece', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (33, N'Poland', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (34, N'Lithuania', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (35, N'United Arab Emirates', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (36, N'Andorra', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (37, N'Saudi Arabia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (38, N'Slovakia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (39, N'Latvia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (40, N'Portugal', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (41, N'Qatar', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (42, N'Chile', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (43, N'Brunei Darussalam', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (44, N'Hungary', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (45, N'Bahrain', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (46, N'Croatia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (47, N'Oman', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (48, N'Argentina', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (49, N'Russian Federation', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (50, N'Belarus', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (51, N'Kazakhstan', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (52, N'Bulgaria', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (53, N'Montenegro', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (54, N'Romania', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (55, N'Palau', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (56, N'Barbados', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (57, N'Kuwait', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (58, N'Uruguay', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (59, N'Turkey', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (60, N'Bahamas', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (61, N'Malaysia', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (62, N'Seychelles', 1)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (63, N'Serbia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (64, N'Trinidad and Tobago', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (65, N'Iran (Islamic Republic of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (66, N'Mauritius', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (67, N'Panama', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (68, N'Costa Rica', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (69, N'Albania', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (70, N'Georgia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (71, N'Sri Lanka', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (72, N'Cuba', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (73, N'Saint Kitts and Nevis', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (74, N'Antigua and Barbuda', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (75, N'Bosnia and Herzegovina', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (76, N'Mexico', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (77, N'Thailand', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (78, N'Grenada', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (79, N'Brazil', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (80, N'Colombia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (81, N'Armenia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (82, N'Algeria', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (83, N'North Macedonia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (84, N'Peru', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (85, N'China', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (86, N'Ecuador', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (87, N'Azerbaijan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (88, N'Ukraine', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (89, N'Dominican Republic', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (90, N'Saint Lucia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (91, N'Tunisia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (92, N'Mongolia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (93, N'Lebanon', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (94, N'Botswana', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (95, N'Saint Vincent and the Grenadines', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (96, N'Jamaica', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (97, N'Venezuela (Bolivarian Republic of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (98, N'Dominica', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (99, N'Fiji', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (100, N'Paraguay', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (101, N'Suriname', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (102, N'Jordan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (103, N'Belize', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (104, N'Maldives', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (105, N'Tonga', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (106, N'Philippines', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (107, N'Moldova (Republic of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (108, N'Turkmenistan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (109, N'Uzbekistan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (110, N'Libya', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (111, N'Indonesia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (112, N'Samoa', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (113, N'South Africa', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (114, N'Bolivia (Plurinational State of) ', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (115, N'Gabon', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (116, N'Egypt', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (117, N'Marshall Islands', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (118, N'Viet Nam', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (119, N'Palestine, State of', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (120, N'Iraq', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (121, N'Morocco', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (122, N'Kyrgyzstan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (123, N'Guyana', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (124, N'El Salvador', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (125, N'Tajikistan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (126, N'Cabo Verde', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (127, N'Guatemala', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (128, N'Nicaragua', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (129, N'India', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (130, N'Namibia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (131, N'Timor-Leste', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (132, N'Honduras', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (133, N'Kiribati', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (134, N'Bhutan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (135, N'Bangladesh', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (136, N'Micronesia (Federated States of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (137, N'Sao Tome and Principe', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (138, N'Congo', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (139, N'Eswatini (Kingdom of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (140, N'Lao People''s Democratic Republic', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (141, N'Vanuatu', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (142, N'Ghana', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (143, N'Zambia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (144, N'Equatorial Guinea', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (145, N'Myanmar', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (146, N'Cambodia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (147, N'Kenya', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (148, N'Nepal', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (149, N'Angola', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (150, N'Cameroon', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (151, N'Zimbabwe', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (152, N'Pakistan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (153, N'Solomon Islands', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (154, N'Syrian Arab Republic', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (155, N'Papua New Guinea', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (156, N'Comoros', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (157, N'Rwanda', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (158, N'Nigeria', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (159, N'Tanzania (United Republic of)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (160, N'Uganda', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (161, N'Mauritania', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (162, N'Madagascar', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (163, N'Benin', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (164, N'Lesotho', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (165, N'Côte d''Ivoire', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (166, N'Senegal', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (167, N'Togo', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (168, N'Sudan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (169, N'Haiti', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (170, N'Afghanistan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (171, N'Djibouti', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (172, N'Malawi', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (173, N'Ethiopia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (174, N'Gambia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (175, N'Guinea', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (176, N'Liberia', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (177, N'Yemen', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (178, N'Guinea-Bissau', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (179, N'Congo (Democratic Republic of the)', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (180, N'Mozambique', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (181, N'Sierra Leone', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (182, N'Burkina Faso', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (183, N'Eritrea', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (184, N'Mali', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (185, N'Burundi', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (186, N'South Sudan', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (187, N'Chad', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (188, N'Central African Republic', 2)
INSERT INTO [dbo].[Country] ([Id], [Name], [CountryTypeId]) VALUES (189, N'Niger', 2)
SET IDENTITY_INSERT [dbo].[Country] OFF
